---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tbz-sample-app-web-tls
spec:
  commonName: sample-app-{{ .Release.Name }}
  dnsNames:
  - sample-app-{{ .Release.Name }}.example.test
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: {{ .Release.Name }}-tbz-sample-app-web-tls
  subject:
    organizationalUnits:
    - Kubernetes
    organizations:
    - example.test
                                                                        