---
apiVersion: v1
kind: Service
metadata:
  name: staging-tbz-sample-app-web
  labels:
    app.kubernetes.io/name: tbz-sample-app
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tbz-sample-app
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: staging
