---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-web-tls"
spec:
  commonName: "{{ .Values.web.ingress.hostname }}"
  dnsNames:
  - "{{ .Values.web.ingress.hostname }}"
  issuerRef:
    kind: "{{ .Values.web.ingress.issuerKind }}"
    name: "{{ .Values.web.ingress.issuerName }}"
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: "{{ .Release.Name }}-{{ .Chart.Name }}-web-tls"

                                                                        