---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: "{{ .Values.db.service.type }}"
  ports:
    - port: "{{ .Values.db.service.portNumber }}"
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: {{ .Release.Name }}