---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-tbz-sample-app-web-tls
spec:
  commonName: sample-app-staging
  dnsNames:
  - sample-app-staging.example.test
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: staging-tbz-sample-app-web-tls
  subject:
    organizationalUnits:
    - Kubernetes
    organizations:
    - example.test
