---
apiVersion: v1
kind: Service
metadata:
  name: staging-tbz-sample-app-db
  labels:
    app.kubernetes.io/name: tbz-sample-app
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: staging
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: tbz-sample-app
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: staging